name: wayfare_travel_planner
description: A Flutter front-end prototype for a Material You travel planning app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.8.1
  http: ^1.5.0
  latlong2: ^0.9.1
  amap_flutter_map:
    path: third_party/amap_flutter_map
  amap_flutter_base:
    path: third_party/amap_flutter_base
  shared_preferences: ^2.5.5
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
